# Welcome to Jekyll!
#

# Site settings
title: Wellness in Paderborn
description: |
  Sauna im privaten Umfeld dort genießen wo du willst
owner: LPT-Wellness GbR # or company name
address: Thüringer Weg 22, 33098 Paderborn
first_published: 2021 # if migrating another site, the year of your first publish
email: info@wellness-pb.de
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.wellness-pb.de # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:info@wellness-pb.de
  whatsapp: https://wa.me/491602017067
  phone: tel:+491602017067
  facebook-official: https://www.facebook.com/mobilesaunapaderborn
  #flickr:
  instagram: https://www.instagram.com/mobile_sauna_paderborn
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:


# Build settings
markdown: kramdown
#sass:
#  style: compressed
